#!/usr/bin/env python3
"""Generate markdown PR summary from sync JSON output."""

import json
import sys
from pathlib import Path

AVG_CHUNKS_PER_FILE = 20
MAX_FILES_PER_SECTION = 30
MAX_BODY_CHARS = 60000


def generate_summary(summary_path: str) -> str:
    with open(summary_path) as f:
        data = json.load(f)

    date = data.get("date", "unknown")
    force = data.get("force", False)
    frameworks = data.get("frameworks", {})
    totals = data.get("totals", {})

    lines = []

    if force:
        lines.append("> **This is a force re-sync.** All files are treated as new.\n")

    lines.append(f"**Date:** {date}\n")

    # Table header
    lines.append("### Changes by Framework\n")
    lines.append("| Framework | New | Modified | Deleted | Unchanged |")
    lines.append("|-----------|-----|----------|---------|-----------|")

    total_unchanged = 0
    for name, fw in sorted(frameworks.items()):
        if fw.get("status") == "failed":
            lines.append(f"| {name} | FAILED | - | - | - |")
            continue
        n = len(fw.get("new", []))
        m = len(fw.get("modified", []))
        d = len(fw.get("deleted", []))
        u = fw.get("unchanged_count", 0)
        total_unchanged += u
        lines.append(f"| {name} | {n} | {m} | {d} | {u} |")

    lines.append(
        f"| **Total** | **{totals.get('new', 0)}** | **{totals.get('modified', 0)}** "
        f"| **{totals.get('deleted', 0)}** | **{total_unchanged}** |"
    )

    # Estimated impact
    files_to_embed = totals.get("new", 0) + totals.get("modified", 0)
    est_chunks = files_to_embed * AVG_CHUNKS_PER_FILE
    lines.append("\n### Estimated Impact\n")
    lines.append(f"- Files to embed: {files_to_embed}")
    lines.append(f"- Files to delete: {totals.get('deleted', 0)}")
    lines.append(f"- Estimated chunks to upsert: ~{est_chunks}")

    # Changed files per framework (truncated to fit GitHub's 65K limit)
    lines.append("\n### Changed Files\n")
    for name, fw in sorted(frameworks.items()):
        if fw.get("status") == "failed":
            continue
        new_files = fw.get("new", [])
        mod_files = fw.get("modified", [])
        del_files = fw.get("deleted", [])
        if not new_files and not mod_files and not del_files:
            continue

        total = len(new_files) + len(mod_files) + len(del_files)
        lines.append(f"<details>")
        lines.append(f"<summary><strong>{name}</strong> ({total} files)</summary>\n")

        if new_files:
            lines.append("**New:**")
            for f in sorted(new_files)[:MAX_FILES_PER_SECTION]:
                lines.append(f"- `{f}`")
            if len(new_files) > MAX_FILES_PER_SECTION:
                lines.append(f"- *...and {len(new_files) - MAX_FILES_PER_SECTION} more*")
            lines.append("")

        if mod_files:
            lines.append("**Modified:**")
            for f in sorted(mod_files)[:MAX_FILES_PER_SECTION]:
                lines.append(f"- `{f}`")
            if len(mod_files) > MAX_FILES_PER_SECTION:
                lines.append(f"- *...and {len(mod_files) - MAX_FILES_PER_SECTION} more*")
            lines.append("")

        if del_files:
            lines.append("**Deleted:**")
            for f in sorted(del_files)[:MAX_FILES_PER_SECTION]:
                lines.append(f"- `{f}`")
            if len(del_files) > MAX_FILES_PER_SECTION:
                lines.append(f"- *...and {len(del_files) - MAX_FILES_PER_SECTION} more*")
            lines.append("")

        lines.append("</details>\n")

    lines.append("---")
    lines.append("*Auto-generated by the weekly docs sync. Merge to trigger embedding to Pinecone.*")

    output = "\n".join(lines)
    if len(output) > MAX_BODY_CHARS:
        output = output[:MAX_BODY_CHARS] + "\n\n---\n**(truncated — full diff available on the branch)**"
    return output


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print(f"Usage: {sys.argv[0]} <summary.json>", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    if not Path(path).exists():
        print(f"Error: {path} not found", file=sys.stderr)
        sys.exit(1)

    print(generate_summary(path))
